### ISSUE TITLE
Works perfect until the Diablo II game window is focused.

### ISSUE THREAD

**Issue by eschwar93** [woroniecki/Joypad-To-Keyboard#2]
I can't seem to get the program to apply the mapping when the Diablo II game window is focused. Works fine until I open the game. Continues to work properly when I alt-tab to desktop, but alt-tabbing back into the game makes it stop again. Any ideas?

**Comment by woroniecki** [comment]
Well, first try tu run as admin.
What windows do you have 10 or 7?
Try windowed mod in Diablo II, and also run Diablo II in admin mode.
Give sign if something helped.

**Comment by eschwar93** [comment]
Running as admin worked! Thank you.
