### ISSUE TITLE
Share your D2 mapping?

### ISSUE THREAD

**Issue by solomani** [woroniecki/Joypad-To-Keyboard#3]
Hi, could you share the D2 mapping you used in the demo video?  

Thanks.

**Comment by woroniecki** [comment]
Hi, sure
https://github.com/woroniecki/Joypad-To-Keyboard/tree/master/MapController/Assets/Binds
just change alt to x in settings of Diablo ii, to show loot on the ground﻿

**Comment by solomani** [comment]
Great, thank you.
